### ISSUE TITLE
Code needs to be more object-oriented

### ISSUE THREAD

**Issue by mbaumer** [drphilmarshall/PS1QLS#15]
Refactor so that:
* we have an overarching 'classifier' class that can be XD, RF, etc. with sklearn-like interface for train/test
* we can pickle data objects with many properties?
* we have a section in the notebook starts with import PS1QLS...

**Comment by mbaumer** [comment]
* ROC curve method for classifier object
* XD classifier should own a dud model and a lQSO model to ensure uniform interface wrt RF, etc.

**Comment by drphilmarshall** [comment]
Nice! Can you please post a link to a demo on the README, if you haven't
already?

**Comment by mbaumer** [comment]
I added an updated link and am cleaning up the notebook a bit
