### ISSUE TITLE
Using the OM10 catalog

### ISSUE THREAD

**Issue by mbaumer** [drphilmarshall/PS1QLS#9]
The [OM10 catalog](https://github.com/drphilmarshall/OM10) provides us with a realistic population of simulated lenses. These would have two potential uses for us:

1. Obtaining reasonable priors for our XD-based lQSO probabilities. We'll need priors for the number of lQSOs per square degree, as well as a distribution of lensed quasar magnitudes. (both of these will have to be corrected for PS1-specific completeness effects, etc.)

2. Fundamentally, XD is a mixture-of-gaussians model we fit to our observed data. Can we use XD fits to the color information contained in the OM10 catalog as initializations of our hyperparameters (the means and covariances of each Gaussian component)?

**Comment by mbaumer** [comment]
Hey @drphilmarshall, can you talk to Adri et al about pasting OM10 simulated lenses near LRGs in PS1 data?

**Comment by drphilmarshall** [comment]
Closing this now: see detailed plan at #22
